#pragma once

enum ReplayEventType {
    REVT_SESSION_CREATE = 1, REVT_SESSION_JOIN = 2, REVT_SESSION_LEAVE = 3,
    REVT_MSG_RX = 10, REVT_MSG_TX = 11, REVT_MSG_ERROR = 12,
    REVT_PLAYER_UPDATE = 20, REVT_BUBBLE_EVENT = 21,
    REVT_ACTOR_SPAWN = 30, REVT_ACTOR_UPDATE = 31, REVT_ACTOR_DESPAWN = 32,
    REVT_DAMAGE_RESULT = 40, REVT_DEATH_EVENT = 41,
    REVT_BUILD_REQ = 50, REVT_BUILD_RESULT = 51, REVT_OBJECT_SPAWN = 52, REVT_OBJECT_UPDATE = 53, REVT_OBJECT_DESPAWN = 54,
    REVT_PROFILE_LOAD = 60, REVT_PROFILE_SAVE = 61
};
