#pragma once

#define F4MP_MAX_PACKET_SIZE           1400
#define F4MP_MAX_MESSAGES_PER_PACKET   32
#define F4MP_MAX_PLAYER_NAME_BYTES     64
#define F4MP_MAX_PLAYER_GUID_BYTES     64
#define F4MP_MAX_DIALOGUE_TEXT_BYTES   512
#define F4MP_MAX_OBJECTIVES_PER_QUEST  16
#define F4MP_MAX_DIALOGUE_CHOICES      12
#define F4MP_MAX_CELL_IDS              128

